export const productData = [
  {
    id: 1,
    title: 'Lenovo IdeaPad L3',
    description: `The Lenovo IdeaPad L3 has everything you need from a laptop for everyday use. However, models with more RAM and high-performance Intel® processors are also available. These are ideal devices for those who need something more than just access to the Internet. An FHD display, stereo speakers and a long battery life let you enjoy your favorite movies and TV series wherever you are. At work, at school and at home, the IdeaPad L3 has a place everywhere.
              Opt for a model with a 10th Gen Intel® Core™ processor and up to 16GB of RAM and a world of new possibilities will open up before you: use demanding applications for photo and video editing, play the latest games and perform many other tasks.
             The Dolby Audio™-enabled speaker system and narrow bezel FHD display are purpose-built to bring your favorite videos to life, immersed in rich colors and surround sound.
             Wherever you go, the IdeaPad L3 is your go-to laptop with up to 11 hours of battery life. And if you do need to recharge, Rapid Charge technology allows you to replenish up to 80% of the charge in less than an hour, and you can immediately return to your activities.`,
    price: 930.85,
    discountPrice: 809.84,
    discountPercentage: 12.96,
    rating: 4.75,
    stock: 72,
    color: 'silver',
    brand: 'Lenovo',
    category: 'laptop',
    images: [
      '../../assets/img/71742465351-l.jpg',
      '../../assets/img/71742465352-l.jpg',
      '../../assets/img/71742465353-l.jpg',
      '../../assets/img/71742465354-l.jpg',
    ],
  },
  {
    id: 2,
    title: 'IPhone 9',
    description: `The design of IPhone 9 64GB will repeat the "eighth" version, but the classic body will be thicker to accommodate a larger battery. The round Home button will return, where Touch ID (fingerprint scanner) is located. Most likely, the rear panel of the device will be matte, it will house a mid-range single camera.
    IPhone 9 will appeal to connoisseurs of flagship devices with moderate dimensions and small monitor.
    Part of the internal filling will be taken from last year's top "eleventh" series. The productivity of the 6-core processor of the new generation A13 Bionic will allow the gadget to execute commands and tasks faster by 20%. Its production is based on the 7nm process technology with the 3rd generation Neural Engine system.
    The product with 64 GB of internal memory will be equipped with 3 GB of RAM and a graphics coprocessor of its own brand design. The IPhone 9 runs on the proprietary operating system iOS 13.`,
    price: 256,
    discountPrice: 240.64,
    discountPercentage: 5.7,
    rating: 4.69,
    stock: 94,
    color: 'white',
    brand: 'Apple',
    category: 'smartphone',
    images: [
      '../../assets/img/71742465251-l.jpg',
      '../../assets/img/71742465252-l.jpg',
      '../../assets/img/71742465253-l.jpg',
      '../../assets/img/71742465254-l.jpg',
    ],
  },
  {
    id: 3,
    title: 'IPhone X',
    description: `Apple IPhone X is the embodiment of the best innovative solutions. Completely new design with a rethought control system. The bezel-less design takes the user experience to the next level. Body made of glass and metal. The perfect hardware core, thanks to the most powerful internal 64-bit architecture. The dramatically improved world's most popular mobile camera.
      The usual Touch ID fingerprint recognition system has been replaced by a powerful and secure Face ID authentication system - recognizing a user by his face. Powered by machine learning technology, the A11 Bionic recognizes you even in a new look. So experiment with haircuts, wear glasses, change hats. And let your friends wonder if it's you - the IPhone X will never make a mistake.
      The 6-core A11 Bionic processor delivers unparalleled speed for IPhone X. Productivity increased by 25% and energy efficiency by 70%. The new iPhone has become even faster and copes with everyday activities with minimal energy consumption.`,
    price: 381,
    discountPrice: 331.47,
    discountPercentage: 12.5,
    rating: 4.87,
    stock: 34,
    color: 'silver',
    brand: 'Apple',
    category: 'smartphone',
    images: [
      '../../assets/img/78520465551-l.jpg',
      '../../assets/img/78520465552-l.jpg',
      '../../assets/img/78520465553-l.jpg',
      '../../assets/img/78520465554-l.jpg',
    ],
  },
  {
    id: 4,
    title: 'Iiyama ProLite',
    description:
      'Iiyama ProLite is a stylish edge-to-edge monitor ideal for multi-monitor setups in both the office and home. IPS panel technology provides accurate and stable color reproduction with wide viewing angles, while 4K resolution allows you to display 4 times more information than a FullHD monitor. In addition, the ProLite XUB2893UHSU is equipped with HDMI and DisplayPort digital inputs, and high contrast and brightness values mean that the monitor will provide excellent performance for photography and web design. The height-adjustable stand makes it easy to adjust the screen to your preference.',
    price: 697.6,
    discountPrice: 537.15,
    discountPercentage: 23,
    rating: 4.09,
    stock: 28,
    color: 'black',
    brand: 'Iiyama',
    category: 'monitor',
    images: [
      '../../assets/img/96712477511-l.jpg',
      '../../assets/img/96712477512-l.jpg',
      '../../assets/img/96712477513-l.jpg',
      '../../assets/img/96712477514-l.jpg',
    ],
  },
  {
    id: 5,
    title: 'Oppo A53',
    description: `The lightweight and ultra-thin Oppo A53 is designed to fit comfortably in one hand. And its design, inspired by the shining translucent reflection of ocean waves, makes the look of the smartphone not only elegant, but also attractive.
    Get the most out of everything you do with a screen with a high refresh rate of 90Hz. It not only occupies almost 90% of the entire surface of the front panel, but also provides more comfortable and smooth operation. Watch videos, play games and keep up with the latest trends, enjoying every touch of the display.
    A large capacity 5000 mAh battery combined with support for high-speed 18-watt charging will allow you to focus on your business instead of searching for an outlet. In addition, the phone has an advanced power saving mode, which helps to extend the time of its operation, so that you can stay connected no matter what.
    Thanks to the efficient Qualcomm Snapdragon processor, you can calmly communicate via video call, watch movies and do many other things. No annoying waiting or hangs. What's more, the use of fast LPDDR4x RAM and UFS2.1 type storage further reduces the lag time when launching applications and opening files.`,
    price: 201,
    discountPrice: 201.0,
    discountPercentage: 0,
    rating: 4.3,
    stock: 123,
    color: 'blue',
    brand: 'Oppo',
    category: 'smartphone',
    images: [
      '../../assets/img/96865477511-l.jpg',
      '../../assets/img/96865477512-l.jpg',
      '../../assets/img/96865477513-l.jpg',
      '../../assets/img/96865477514-l.jpg',
    ],
  },
  {
    id: 6,
    title: 'Huawei Matebook X Pro',
    description: `Huawei MateBook X Pro is equipped with a sensitive touch screen on which you can perform scrolling, zooming and pressing gestures for even more convenient and intuitive control. Now the touchscreen allows you to take a screenshot in an instant: just swipe the screen with three fingers.
      A professional laptop that does not take up much space in your bag. The elegant diamond-cut and sandblasted metal body is about 14.6mm thick and weighs just 1.33kg. Carry MateBook X Rgo with you always and everywhere.
      Huawei MateBook X Pro is an improved Intel Core i7 processor of the 10th generation, a discrete NVIDIA GeForce MX250 video card, 16 GB of RAM and 1 TB of SSD storage. The power of the laptop is enough to perform all the tasks you need. Thanks to the powerful hardware, Huawei MateBook X Pro supports multitasking, fast image processing and smooth frame changes in games. The updated high-speed Wi-Fi module and the Bluetooth 5.0 standard guarantee a smooth connection.`,
    price: 1075,
    discountPrice: 956.75,
    discountPercentage: 10.58,
    rating: 4.09,
    stock: 32,
    color: 'green',
    brand: 'Huawei',
    category: 'laptop',
    images: [
      '../../assets/img/97875477511-l.jpg',
      '../../assets/img/97875477512-l.jpg',
      '../../assets/img/97875477513-l.jpg',
      '../../assets/img/97875477514-l.jpg',
    ],
  },
  {
    id: 7,
    title: 'Apple MacBook Pro M2',
    description: `Take your work to a new level of professionalism and reach new heights in creativity with the new 13-inch MacBook Pro. It is equipped with a completely new, more productive M2 chip, which makes the laptop even more functional and fast. With a beautiful Retina display, HD FaceTime camera and studio-quality microphones, your work and communication will become even better, and the active cooling system will make sure that the pace does not decrease even during heavy workloads. And all this in an incredibly compact design and with a battery that provides up to 20 hours of battery life.
    The notebook is based on the next generation of Apple M2 chips. This powerful 8-core processor is even faster and more energy efficient than the previous M1. Together with a lightning-fast 10-core GPU, it enables faster processing of photos and videos, creates stunning graphics and works with a large number of 4K and 8K ProRes video streams. And also increases game performance. Thus, this portable professional laptop will allow you to work, create and have fun on a completely different level.
    Focus on what's important to you, and MacBook Pro M2 will make sure you have enough time to do it all. Its battery can provide up to 20 hours of autonomous operation, which allows you to work freely without being tied to one place.`,
    price: 1375,
    discountPrice: 1223.75,
    discountPercentage: 11.02,
    rating: 4.57,
    stock: 83,
    color: 'silver',
    brand: 'Apple',
    category: 'laptop',
    images: [
      '../../assets/img/97875233511-l.jpg',
      '../../assets/img/97875233512-l.jpg',
      '../../assets/img/97875233513-l.jpg',
      '../../assets/img/97875233514-l.jpg',
    ],
  },
  {
    id: 8,
    title: 'Samsung Galaxy Book Pro',
    description: `AMOLED display, now also on the Samsung Galaxy Book Pro!
    Enjoy the same vibrant colors, contrast and fast response times as your Samsung Galaxy phone. On an AMOLED screen, games, movies, photos and websites are more accurate and vibrant in color, the screen responds faster and emits less harmful blue light.
    Create a wireless connection and share images, videos or files with other users by pressing the share button and selecting the icons of people nearby. You can also send documents to a group at the same time.
    Connect Samsung Galaxy Book Pro and Samsung Galaxy Buds together. Open the headphone case next to your laptop and the connection is complete. Very simple!
    Connect your home to the network and control all your smart products with SmartThings. Now you can find your Samsung Galaxy book with SmartThings Find.`,
    price: 899,
    discountPrice: 863.04,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    color: 'white',
    brand: 'Samsung',
    category: 'laptop',
    images: [
      '../../assets/img/12345233511-l.jpg',
      '../../assets/img/12345233512-l.jpg',
      '../../assets/img/12345233513-l.jpg',
      '../../assets/img/12345233514-l.jpg',
    ],
  },
  {
    id: 9,
    title: 'Apple iPhone 14',
    description: `Meet the new model of the legendary smartphone! The iPhone 14 will be able to please you with an ultra-durable body made of aerospace-grade aluminum and a reliable protected display created by Corning: Ceramic Shield technology. Also, iPhone 14 and iPhone 14 Plus are perfectly resistant to splashes of water and dust thanks to the IP68 standard. The bright and rich Super Retina XDR display will not leave any user indifferent. Improved autonomy allows you to actively use the new iPhone throughout the day. Updated cameras and photo processing algorithms will give you the opportunity to create even better photos even in low light conditions. APPLE iPhone 14 is equipped with a super-fast A15 Bionic processor, which has 5 graphic cores.
      High resolution makes it possible to display the maximum number of details, making the picture more alive and natural. And the special True Tone function will control the brightness and harmful blue radiation from the screen, thanks to which you will be able to better see the image on the display at noon, and when viewing content in the evening and at night (in poor lighting conditions), your eyes will not tire quickly. The diagonal of the iPhone 14 is 6.1 inches.`,
    price: 1087.5,
    discountPrice: 1000.5,
    discountPercentage: 7.8,
    rating: 5,
    stock: 51,
    color: 'red',
    brand: 'Apple',
    category: 'smartphone',
    images: [
      '../../assets/img/23455233511-l.jpg',
      '../../assets/img/23455233512-l.jpg',
      '../../assets/img/23455233513-l.jpg',
      '../../assets/img/23455233514-l.jpg',
    ],
  },
  {
    id: 10,
    title: 'Apple IPad 10',
    description: `The all-new iPad has been dramatically reimagined to become more functional, more intuitive, and even more exciting. With a new full-screen design, 10.9-inch Liquid Retina display and four gorgeous colors, iPad offers a powerful way to get things done, create and stay connected.
    Get things done—all on one device. Take notes, collaborate, and work seamlessly between apps. From pie charts to pie recipes, iPad is designed for any productivity.
    The A14 Bionic chip provides power and performance for any activity. Edit 4K videos in iMovie, plan a world trip with friends, or play graphics-intensive games. With an all-day battery, you can do everything without missing a second.
    Express yourself, draw and brainstorm on a flexible creative platform. The stunning 10.9-inch Liquid Retina display creates an incredible canvas. So you can draw, take notes, mark up documents and more with Apple Pencil (sold separately).`,
    price: 847,
    discountPrice: 745.36,
    discountPercentage: 11.83,
    rating: 4.54,
    stock: 96,
    color: 'yellow',
    brand: 'Apple',
    category: 'tablet',
    images: [
      '../../assets/img/34565233511-l.jpg',
      '../../assets/img/34565233512-l.jpg',
      '../../assets/img/34565233513-l.jpg',
    ],
  },
  {
    id: 11,
    title: 'HP Victus 16-e0151ur',
    description: `The HP Victus 16 gaming laptop is equipped with a luscious 16.1-inch screen, a powerful AMD Ryzen 5 5600H (Zen 3) 3.3 GHz processor, NVIDIA GeForce® RTX 3050 professional graphics for laptop, and an excellent cooling system. The HP Victus 16 model is interesting for users who often play with a laptop and work with video editors. HP Victus 16 gaming laptop are popular with customers due to the large selection of configurations, the highest quality of goods and an excellent price.`,
    price: 1099,
    discountPrice: 1033.06,
    discountPercentage: 6.18,
    rating: 4.43,
    stock: 89,
    color: 'black',
    brand: 'HP',
    category: 'laptop',
    images: [
      '../../assets/img/11037535671-l.jpg',
      '../../assets/img/11037535672-l.jpg',
      '../../assets/img/11037535674-l.jpg',
      '../../assets/img/11037535675-l.jpg',
    ],
  },
  {
    id: 12,
    title: 'Realme 9 Pro+',
    description:
      'The Realme 9 Pro+ smartphone has 3 main cameras: 50 + 8 + 4 megapixels that allow you to shoot 4K video, take excellent portraits with bokeh effect, panoramic shots and photos of distant objects, slow motion at 960 fps. The 16 MP front camera makes it possible to take great selfies. The Super AMOLED display with a resolution of 2400x1080 will amaze you with bright, rich and deep blacks. A capacious 4500 mAh battery is enough for a long battery life. The supplied 60W power adapter will help you quickly replenish the charge. An in-display fingerprint scanner and software face unlock protect your data if your device is lost. An NFC module is provided for contactless payment.',
    price: 368,
    discountPrice: 368.0,
    discountPercentage: 0,
    rating: 4.58,
    stock: 5,
    color: 'black',
    brand: 'Realme',
    category: 'smartphone',
    images: [
      '../../assets/img/71114058551-l.jpg',
      '../../assets/img/71114058553-l.jpg',
      '../../assets/img/71114058554-l.jpg',
      '../../assets/img/71114058555-l.jpg',
    ],
  },
  {
    id: 13,
    title: 'Xiaomi Redmi Watch 2',
    description:
      'Get in shape, start right now. 100+ workout modes. Track your exercises like an expert. Switch freely between over 100 watch faces with multiple trend-setting combinations to suit your mood.',
    price: 70.65,
    discountPrice: 67.82,
    discountPercentage: 4.23,
    rating: 3.85,
    stock: 12,
    color: 'white',
    brand: 'Xiaomi',
    category: 'smartwatch',
    images: [
      '../../assets/img/48367418351-l.jpg',
      '../../assets/img/48367418352-l.jpg',
      '../../assets/img/48367418353-l.jpg',
    ],
  },
  {
    id: 14,
    title: 'Huawei MatePad Pro',
    description:
      'The color design of Huawei MatePad Pro is inspired by nature. The midnight gray body is covered with a layer of fiberglass that reflects the light and reflects your unique style. Compact and lightweight, weighing only 460g, it is easy to carry everywhere with you. It feels like a simple sheet of paper in a backpack.The hidden antenna gives the tablet a sleek and finished look, while the thin, slightly rounded bezel makes the tablet comfortable to use.',
    price: 707.8,
    discountPrice: 672.41,
    discountPercentage: 5.36,
    rating: 4.25,
    stock: 23,
    color: 'silver',
    brand: 'Huawei',
    category: 'tablet',
    images: ['../../assets/img/14380352311-l.jpg', '../../assets/img/14380352312-l.jpg'],
  },
  {
    id: 15,
    title: 'MSI Pro AP241',
    description: `With powerful processing power and an ergonomic 23.8 screen, the PRO AP241 All-in-One PC will help you work more productively and comfortably. Available in two color options, the slim design fits perfectly into your modern home or office environment.
    To protect the user's eyes and improve comfort during long stays at the computer, the all-in-one has implemented special technologies that suppress screen flicker MSI Anti-Flicker and reduce the intensity of blue light MSI Less Blue Light. In addition, the screen is equipped with a matte finish MSI Anti-Glare, which eliminates light reflections.
    To work even more efficiently with large amounts of data, a second monitor (up to 4K / 60 Hz) can be connected to the PRO AP241 all-in-one via HDMI 2.0. It will also be a good solution for video conferencing using MSI's FHD camera.`,
    price: 1681.42,
    discountPrice: 1681.42,
    discountPercentage: 0,
    rating: 4.75,
    stock: 3,
    color: 'black',
    brand: 'MSI',
    category: 'monoblock',
    images: [
      '../../assets/img/52026264101-l.jpg',
      '../../assets/img/52026264102-l.jpg',
      '../../assets/img/52026264103-l.jpg',
      '../../assets/img/52026264104-l.jpg',
    ],
  },
  {
    id: 16,
    title: 'Apple TV 4K',
    description: `The new Apple TV 4K combines the best TV content with the gigantic potential of Apple devices and services. Now your living room will be truly transformed.
    Picture and sound like in real life. Apple TV 4K with Dolby Vision will make all your entertainment unforgettable. And if your sound system supports Dolby Atmos1, Apple TV 4K will turn your home into a real theater and you can fully immerse yourself in surround sound.
    Apple TV 4K can play video at twice the frame rate of HDR, so colors look more realistic and images are crisper. Even fast-moving events, such as during a sports broadcast, can be viewed in great detail. Nature on the screen looks incredibly realistic. And YouTube videos literally come to life.
    Sometimes adjusting the picture on the TV turns into a long and complicated process. But not with Apple TV 4K. You should now be able to automatically calibrate the image using your iPhone. Just point your iPhone at your TV screen once, then sit back and watch movies and TV shows in a new amazing quality.`,
    price: 396.3,
    discountPrice: 376.49,
    discountPercentage: 4.69,
    rating: 3.27,
    stock: 15,
    color: 'black',
    brand: 'Apple',
    category: 'TV-box',
    images: [
      '../../assets/img/81802826001-l.jpg',
      '../../assets/img/81802826002-l.jpg',
      '../../assets/img/81802826005-l.jpg',
      '../../assets/img/81802826004-l.jpg',
    ],
  },
  {
    id: 17,
    title: 'Alienware AW2720HFA',
    description: `Advantage in every moment of the fight. Victory in every fight. The incredible responsiveness and depth of gaming monitor immersion make the Alienware 27 the ideal choice for gamers.
    The unrivaled IPS panel has a native refresh rate of up to 240Hz: 10x faster than a movie theater and 2x faster than conventional 120Hz gaming monitor.
    Response time 1 ms. No tricks. Real 1ms response time and Overdrive technology deliver fast, responsive, distortion-free gaming.
    AMD FreeSync technology keeps your graphics card and monitor in sync, so you get stunning full-size images without slowing down your gaming experience. This Alienware 27" monitor also supports NVIDIA G-SYNC technology.
    The new high-speed IPS gaming sensor delivers a true 1ms response time without the use of anti-blur algorithms that affect brightness, adaptive sync, and game world display.
    Saturated image. IPS (In-Planar Switching) technology guarantees high color saturation regardless of the viewing angle.
    Color gamut up to 99% sRGB provides the widest color gamut for your gaming arsenal.`,
    price: 733.38,
    discountPrice: 704.04,
    discountPercentage: 4.15,
    rating: 4.89,
    stock: 9,
    color: 'white',
    brand: 'Alienware',
    category: 'monitor',
    images: [
      '../../assets/img/22069224421-l.jpg',
      '../../assets/img/22069224422-l.jpg',
      '../../assets/img/22069224423-l.jpg',
      '../../assets/img/22069224424-l.jpg',
    ],
  },
  {
    id: 18,
    title: 'Acer Aspire C27-1655',
    description: `The latest Intel processors deliver incredible performance for the most demanding tasks and modern content editing. And with DDR4 RAM, you can multitask unlimited applications. The 27-inch FHD IPS screen delivers true-to-life colors and sharp images. View images with family and friends. Colors stay consistent even at 178° angles`,
    price: 1797.18,
    discountPrice: 1617.46,
    discountPercentage: 10.25,
    rating: 3.79,
    stock: 34,
    color: 'silver',
    brand: 'Acer',
    category: 'monoblock',
    images: [
      '../../assets/img/78686371951-l.jpg',
      '../../assets/img/78686371952-l.jpg',
      '../../assets/img/78686371953-l.jpg',
    ],
  },
  {
    id: 19,
    title: 'Apple Macbook Pro Late 2021',
    description: `We've built the most powerful MacBook Pro ever. And it's a monster. The super-fast M1 Pro and M1 Max are the first Apple chips designed specifically for professionals. They deliver phenomenal performance and provide amazingly long battery life. Add to that a stunning Liquid Retina XDR display, superior camera and sound, and more ports for professional work. Everything is possible with this laptop.`,
    price: 2875,
    discountPrice: 2558.75,
    discountPercentage: 10.5,
    rating: 4.89,
    stock: 14,
    color: 'silver',
    brand: 'Apple',
    category: 'laptop',
    images: [
      '../../assets/img/58651378731-l.jpg',
      '../../assets/img/58651378733-l.jpg',
      '../../assets/img/58651378735-l.jpg',
      '../../assets/img/58651378736-l.jpg',
    ],
  },
  {
    id: 20,
    title: 'Apple iPhone 13 mini',
    description: `IPhone 13 mini have been completely reimagined. The new models feature a sleek aluminum chassis with a durable flat bezel and are available in five stunning colours. The OLED display is energy efficient and has high contrast even in bright sunlight. A durable housing is reliably protected from water and dust.
    The A15 Bionic chip is responsible for the excellent performance of games with complex graphics, as well as the operation of new camera features such as the Cinematic Effect mode and Photo Styles. And the new chip increases the battery life.`,
    price: 1337.85,
    discountPrice: 1337.85,
    discountPercentage: 0,
    rating: 5,
    stock: 25,
    color: 'blue',
    brand: 'Apple',
    category: 'smartphone',
    images: [
      '../../assets/img/59631534211-l.jpg',
      '../../assets/img/59631534212-l.jpg',
      '../../assets/img/59631534213-l.jpg',
      '../../assets/img/59631534215-l.jpg',
    ],
  },
  {
    id: 21,
    title: 'Prestigio Q Pro',
    description: `Equipped with an 8-inch HD screen, the tablet reproduces bright and vivid content. The IPS-matrix guarantees natural color reproduction and wide viewing angles, which allows you to look at the screen from any direction without distorting the picture. Made of durable textured plastic, the tablet provides a pleasant visual and tactile experience. The case can be easily gripped with one hand and be sure that it will not slip out. Plus, there is scratch protection.
    The amount of built-in memory in the tablet was 16 GB, but this is far from the limit. In the existing slot, you can install a microSD memory card and expand the internal storage up to 128 GB. That's enough to store thousands of photos and videos!
    Powered by a quad-core processor in tandem with 2GB of RAM, the tablet will be an excellent choice for solving a variety of tasks: from chatting in a messenger to playing videos.
    With a 5,000 mAh battery and fast 4G connectivity, you can stay connected wherever you are. A capacious battery will ensure that the charge does not run out at the most inopportune moment, and support for 4G networks will allow you to make calls and access the Internet, even if there is no Wi-Fi nearby.`,
    price: 102.81,
    discountPrice: 94.59,
    discountPercentage: 7.8,
    rating: 3.2,
    stock: 8,
    color: 'blue',
    brand: 'Prestigio',
    category: 'tablet',
    images: [
      '../../assets/img/24956794612-l.jpg',
      '../../assets/img/24956794613-l.jpg',
      '../../assets/img/24956794614-l.jpg',
      '../../assets/img/24956794615-l.jpg',
    ],
  },
  {
    id: 22,
    title: 'Samsung Galaxy Tab S8+',
    description: `The Samsung Galaxy tablet leaves a lasting impression. Robust reinforced aluminum construction. Elements as part of a whole: from the magnetic S Pen holder to the camera. Enjoy your favorite movies and games on the big bright screen. Bigger screen size and thinner bezels so you can see more. The fastest processor ever installed in the Galaxy Tab series (4 nm). Console-level games run fast, smooth, and flawlessly - just the way they should be. Battery for the whole day. Seamless multitasking, uninterrupted immersion, long video playback with a powerful battery. Immerse yourself in your favorite games and movies with the most realistic cinematic sound possible thanks to four speakers. Enjoy deep, bass-rich sound with the Tab S8 series.`,
    price: 1125,
    discountPrice: 922.5,
    discountPercentage: 18.45,
    rating: 4.6,
    stock: 22,
    color: 'silver',
    brand: 'Samsung',
    category: 'tablet',
    images: [
      '../../assets/img/78555782811-l.jpg',
      '../../assets/img/78555782812-l.jpg',
      '../../assets/img/78555782813-l.jpg',
    ],
  },
  {
    id: 23,
    title: 'Amazon Kindle 10',
    description: `Ultra-thin case included! Introducing the Amazon Kindle 10 2020 in white. Perhaps this is the simplest and most affordable reader from Amazon. The Kindle 10 2020 e-reader has 8GB of pre-installed memory and a built-in screen backlight that you can adjust yourself. This Kindle 10 2020 model already comes with an ultra-thin UltraSlim case with a magnet and automatic screen off when closed. The Kindle 10 features a next-generation glare-free display, which means it's as close to real paper as possible. This reader is supplied as a Special Offers version (advertised version). Advertising in the form of a screensaver absolutely does not interfere with reading books and does not appear on the pages in the device. Moreover, it can be turned off completely free of charge if it bothers you a lot.`,
    price: 133.7,
    discountPrice: 121.67,
    discountPercentage: 8.5,
    rating: 4.3,
    stock: 2,
    color: 'white',
    brand: 'Amazon',
    category: 'ebook',
    images: [
      '../../assets/img/44114653771-l.jpg',
      '../../assets/img/44114653773-l.jpg',
      '../../assets/img/44114653775-l.jpg',
      '../../assets/img/44114653776-l.jpg',
    ],
  },
  {
    id: 24,
    title: 'HP OMEN 27C',
    description: `What do you prioritize when choosing a gaming monitor? Excellent graphics and high pixel response? Excellent image quality due to high resolution and large screen size? Smart ergonomics? Comfortable viewing angles? It's all important, the optimal gaming machine is made up of a combination of these qualities And the HP OMEN 27c [35D67AA#ABB] 27" Monitor has them all. The 1000R curvature follows the natural shape of your eye, so your eyes make fewer small movements and less fatigue. With a resolution of 2560x1440, you get a juicy three-dimensional and bright picture. , with 178°/178° viewing angles, can be repositioned in front of the HP OMEN 27c [35D67AA#ABB] without compromising image quality.Device pixel time is as low as 1ms.For maximum convenience, the monitor is equipped with a 2-port USB hub. In addition, you can adjust the tilt and height of the monitor.`,
    price: 1051,
    discountPrice: 1051,
    discountPercentage: 0,
    rating: 4.3,
    stock: 27,
    color: 'black',
    brand: 'HP',
    category: 'monitor',
    images: [
      '../../assets/img/60847696571-l.jpg',
      '../../assets/img/60847696572-l.jpg',
      '../../assets/img/60847696573-l.jpg',
      '../../assets/img/60847696574-l.jpg',
    ],
  },
  {
    id: 25,
    title: 'Xiaomi RedmiBook Pro 15',
    description: `RedmiBook 15" Pro laptop with 3.2K Super Retina display supports 90Hz frame rate. Powered by a powerful 11th Gen Intel Core processor and GeForce MX450 graphics card, the device can handle complex graphics programs and games perfectly. The gadget has a 70Wh battery and Able to work on a single charge for about 12 hours.
    The laptop is equipped with a 15.6-inch Super Retina display with a resolution of up to 3.2K. The brightness index is 300 cd / m², and the pixel density is 242 dpi. Feel completely immersed in a game or an exciting movie. The screen of the device is updated up to 90 times per second, so that the dynamic image will be smoother.
    The case of Xiaomi RedmiBook 15" Pro is made of aircraft-grade aluminum alloy. It has gone through 17 grinding processes to achieve a flawless surface texture. The thickness of the laptop is 16.4 mm and its weight does not exceed 1.79 kg.
    High performance is provided by the built-in 11th generation Intel Core processor. The chipset frequency can reach 4.5GHz. Thanks to the optional GeForce MX450 discrete graphics card, the laptop can be used for video editing, gaming and graphics applications.`,
    price: 925,
    discountPrice: 777.0,
    discountPercentage: 15.6,
    rating: 4.64,
    stock: 45,
    color: 'silver',
    brand: 'Xiaomi',
    category: 'laptop',
    images: [
      '../../assets/img/51237623311-l.jpg',
      '../../assets/img/51237623314-l.jpg',
      '../../assets/img/51237623316-l.jpg',
      '../../assets/img/51237623317-l.jpg',
    ],
  },
  {
    id: 26,
    title: 'Xiaomi Poco X4 Pro',
    description: `The Poco X series now uses an AMOLED display and supports DCI-P3 color gamut. Expanded color space for richer picture and cinematic effect. The front camera aperture is 2.96 mm, which expands the field of view. The high-performance Snapdragon processor with 5G offers superior power efficiency and maximum download speeds of 2.5Gbps. POCO X4 Pro 5G is equipped with a large LiquidCool copper heatpipe and multiple layers of graphite sheets for fast heat dissipation and continuous cooling, allowing the device to run at peak performance for longer.
    67W Turbo Charging is capable of incredible things! Thanks to advanced MMT technology, the 5000 mAh battery can be charged up to 100% in 41 minutes!`,
    price: 362.32,
    discountPrice: 336.96,
    discountPercentage: 6.67,
    rating: 3.84,
    stock: 16,
    color: 'yellow',
    brand: 'Xiaomi',
    category: 'smartphone',
    images: [
      '../../assets/img/66910843091-l.jpg',
      '../../assets/img/66910843095-l.jpg',
      '../../assets/img/66910843093-l.jpg',
      '../../assets/img/66910843094-l.jpg',
    ],
  },
  {
    id: 27,
    title: 'Onyx Boox Max Lumi',
    description: `Onyx Boox Max Lumi 2 is the top of the manufacturer's range with a huge 13.3-inch backlit E Ink Mobius Carta screen and dual touch controls. This model is more than just a reader - it is a serious tool for working with textual information. MAX Lumi 2 is perfect for those users who have to read a lot of educational or technical literature, while making notes and drawings in the text. A large, easy-to-read dual-touch e-paper display, combined with a powerful processor and 6 GB of RAM, makes PDF and DjVu files a pleasure to work with. 128 GB of internal memory will allow you to store any necessary books and documents on the reader without any restrictions. The model is based on the Android 11 operating system, which allows you to install and use third-party applications and significantly expands the functionality of the reader. The built-in Wi-Fi module allows you to use various network services, and Bluetooth support allows you to connect external devices. The body of the device is made of light and durable aluminum-magnesium alloy, the screen of the reader is covered with Asahi protective glass.`,
    price: 837.5,
    discountPrice: 837.5,
    discountPercentage: 0,
    rating: 4.9,
    stock: 36,
    color: 'black',
    brand: 'Onyx',
    category: 'ebook',
    images: [
      '../../assets/img/97346480281-l.jpg',
      '../../assets/img/97346480282-l.jpg',
      '../../assets/img/97346480283-l.jpg',
      '../../assets/img/97346480284-l.jpg',
    ],
  },
  {
    id: 28,
    title: 'Samsung Galaxy Watch4',
    description: `Samsung smart watches are not just a gadget, but your faithful companion on the way to achieving goals and self-improvement. The Galaxy Watch4 smart watch is designed to make it easy for us to track and capture the data coming from your body.
    Track your body fat, water, muscle mass, and more, measure your activity level with the Samsung BioActive sensor, set new goals, and make more fitness progress.
    With heart care, the Galaxy Watch4 also features ECG and blood pressure measurement using a PPG sensor.
    For healthy sleep The Galaxy Watch4 has a special tracker that determines the quality of your sleep.
    The Galaxy Watch4 runs on the Samsung-compatible Wear OS platform. This operating system provides fast and stable synchronization with Samsung Galaxy devices, as well as the ability to run your favorite applications right from your wrist.`,
    price: 254.7,
    discountPrice: 198.67,
    discountPercentage: 22,
    rating: 4.25,
    stock: 36,
    color: 'silver',
    brand: 'Samsung',
    category: 'smartwatch',
    images: [
      '../../assets/img/60989942581-l.jpg',
      '../../assets/img/60989942583-l.jpg',
      '../../assets/img/60989942584-l.jpg',
      '../../assets/img/60989942586-l.jpg',
    ],
  },
  {
    id: 29,
    title: 'Digma K1 Dark Grey',
    description: `The e-book is ideal for those who like to read while traveling. Its compact size won't take up much space in your purse or backpack, and the modern E-ink HD Pearl screen will provide maximum comfort even during long reading.
    Support for popular formats will allow you not to think about converting files.`,
    price: 70.65,
    discountPrice: 70.65,
    discountPercentage: 0,
    rating: 3.9,
    stock: 6,
    color: 'silver',
    brand: 'Digma',
    category: 'ebook',
    images: [
      '../../assets/img/91466368401-l.jpg',
      '../../assets/img/91466368402-l.jpg',
      '../../assets/img/91466368403-l.jpg',
      '../../assets/img/91466368404-l.jpg',
    ],
  },
  {
    id: 30,
    title: 'Xiaomi Watch S1',
    description: `The large 1.43-inch AMOLED display, designed with advanced display technology and energy saving, with sapphire crystal coating, brings you a stunning visual experience, turning the slow passage of time into art. Support is always on display.
    Sapphire glass is extremely hard and wear-resistant, its scratch resistance is much higher than that of ordinary glass. The finely carved sapphire glass shines on all sides.
    The watch case adopts 316L austenitic stainless steel, which has unique characteristics of corrosion resistance and scratch resistance, making Xiaomi Watch S1 the most durable Xiaomi watch. Each case is individually polished by traditional watchmakers to give it a precise and streamlined shape. 
    The built-in dual-band GNSS chip supports five major satellite positioning systems: GPS, BeiDou, GLONASS, Galileo and QZSS, as well as advanced optimization algorithms for faster and more accurate positioning, providing you with professional statistics. Supports 117 workout modes including 19 professional workout modes including basketball, tennis, swimming, high intensity interval training and more. Whatever sport you are into, Xiaomi Watch S1 will help you.`,
    price: 257.55,
    discountPrice: 213.77,
    discountPercentage: 17,
    rating: 4.75,
    stock: 15,
    color: 'black',
    brand: 'Xiaomi',
    category: 'smartwatch',
    images: [
      '../../assets/img/11038775561-l.jpg',
      '../../assets/img/11038775562-l.jpg',
      '../../assets/img/11038775563-l.jpg',
      '../../assets/img/11038775564-l.jpg',
    ],
  },
  {
    id: 31,
    title: 'PocketBook 617',
    description: `PocketBook 617 is a unique budget model. Yes, it is controlled by buttons and lacks a touch screen. But it has a number of options that came from top-class readers. This is a backlight with adjustable color temperature. This is support for Wi-Fi and the PocketBook Cloud book-sharing service. This is a powerful dual-core processor. In a word, PocketBook 617 is a solution for economical lovers of the classics, who, nevertheless, want to get an exclusively modern device.`,
    price: 147.24,
    discountPrice: 139.88,
    discountPercentage: 5,
    rating: 4.22,
    stock: 48,
    color: 'black',
    brand: 'PocketBook',
    category: 'ebook',
    images: [
      '../../assets/img/97124123241-l.jpg',
      '../../assets/img/97124123242-l.jpg',
      '../../assets/img/97124123243-l.jpg',
    ],
  },
  {
    id: 32,
    title: 'Huawei P50 Pocket',
    description: `Introducing the next generation Huawei foldable smartphone. Use smart functions when the device is folded and open it to view content on the big screen.
    The glass cover of the smartphone is smooth and shiny. Thanks to the 3D effect, the light is beautifully refracted in it.
    The multi-directional swivel mechanism is made from innovative materials and allows you to easily transform your device from a pocket smartphone to a large screen model.
    The main screen with a diagonal of 6.9 inches and an aspect ratio of 21:9 provides an immersive effect. Experience the smoothness of the interface with a refresh rate of up to 120 Hz. The P3 color gamut reproduces more than 1 billion colors for true-to-life hues. Nano-optical film reduces screen flicker and glare. And thanks to the 1440Hz high-frequency PWM dimming control, the smartphone is comfortable to use even in low-light conditions.
    The innovative Ultra Spectrum Image technology, incorporating Huawei XD Optics image processing algorithms and True-Chroma Image Engine technology, creates bright and high-quality photos with a high level of detail.`,
    price: 864,
    discountPrice: 794.88,
    discountPercentage: 8,
    rating: 3.52,
    stock: 1,
    color: 'white',
    brand: 'Huawei',
    category: 'smartphone',
    images: [
      '../../assets/img/90959172361-l.jpg',
      '../../assets/img/90959172364-l.jpg',
      '../../assets/img/90959172365-l.jpg',
      '../../assets/img/90959172367-l.jpg',
    ],
  },
  {
    id: 33,
    title: 'LG 29WL50S',
    description: `The LG 29WL50S-B [29WL50S-B.ARUZ] monitor is a versatile monitor that is suitable for applications or multimedia content and games. It has a 29-inch IPS panel with a resolution of 2560x1080 pixels, providing high image quality. The HDR10 standard contributes to the achievement of deep shades in the reproduction of the color palette. Anti-reflective coating and eye protection technologies are implemented to enhance comfort. The LG 29WL50S-B [29WL50S-B.ARUZ] monitor is equipped with an HDMI connector and a headphone output. The design of the stand provides the ability to adjust the position by adjusting the angle of inclination forward / backward.`,
    price: 451.52,
    discountPrice: 370.25,
    discountPercentage: 18,
    rating: 4.35,
    stock: 29,
    color: 'black',
    brand: 'LG',
    category: 'monitor',
    images: [
      '../../assets/img/69161952511-l.jpg',
      '../../assets/img/69161952512-l.jpg',
      '../../assets/img/69161952513-l.jpg',
      '../../assets/img/69161952514-l.jpg',
    ],
  },
  {
    id: 34,
    title: 'Samsung Galaxy S21',
    description: `Samsung Galaxy S21 - designed to be the center of events and attention. Capture stunning 8K photos and videos, and capture stunningly clear 33MP photos directly from your video footage. The revolutionary 64MP AI camera analyzes every frame to automatically make it perfect. The fastest processor and powerful battery with a charge for the whole day will allow you to feel free in any situation.
    Feel the events on the screen as if you were living in their epicenter. Experience the full benefits of Dynamic AMOLED 2X technology on a super-smooth 120Hz 6.2-inch screen with stunning color reproduction and clarity even in bright sunlight. Content-optimised refresh rates deliver the ultimate experience, while reducing the harmful effects of blue light reduces eye strain and allows you to enjoy your viewing for as long as you like.`,
    price: 935.27,
    discountPrice: 879.15,
    discountPercentage: 6.2,
    rating: 4.88,
    stock: 10,
    color: 'white',
    brand: 'Samsung',
    category: 'smartphone',
    images: [
      '../../assets/img/44951705371-l.jpg',
      '../../assets/img/44951705372-l.jpg',
      '../../assets/img/44951705373-l.jpg',
    ],
  },
  {
    id: 35,
    title: 'BenQ BL2783',
    description: `BenQ BL2783 will take care of users who spend hours on end exploring the Web, watching movies or working in applications. The monitor blends seamlessly into both office and home environments with its classic design and offers you a range of useful features.`,
    price: 395.45,
    discountPrice: 383.59,
    discountPercentage: 3.2,
    rating: 4.15,
    stock: 2,
    color: 'black',
    brand: 'BenQ',
    category: 'monitor',
    images: [
      '../../assets/img/55528362051-l.jpg',
      '../../assets/img/55528362052-l.jpg',
      '../../assets/img/55528362053-l.jpg',
      '../../assets/img/55528362056-l.jpg',
    ],
  },
  {
    id: 36,
    title: 'Asus TUF Gaming A17',
    description: `If computer games are your element, stop the choice on the Asus TUF Gaming A17 laptop. The presented model meets the highest quality standards. The hardware configuration is based on one of the most modern AMD Ryzen 7 processors and GeForce RTX 3050 graphics card - in any game you will feel at your best. Of particular praise is the textured finish at the base of the case, which pairs perfectly with the ribs and the textured finish at the wrists. Before starting mass production of the presented model, it passed a series of strict quality tests.`,
    price: 1698.9,
    discountPrice: 1410.09,
    discountPercentage: 17.3,
    rating: 4.95,
    stock: 15,
    color: 'black',
    brand: 'Asus',
    category: 'laptop',
    images: [
      '../../assets/img/30706677411-l.jpg',
      '../../assets/img/30706677412-l.jpg',
      '../../assets/img/30706677413-l.jpg',
      '../../assets/img/30706677414-l.jpg',
    ],
  },
  {
    id: 37,
    title: 'Mecool KM6 Classic',
    description: `A new compact set-top box from Mecool - KM6 Classic, which has all the necessary functions for a comfortable pastime in front of TV. It is equipped with the latest Amlogic S905X4 processor with four Cortex A55 cores and has a sufficiently powerful quad-core Mali-G31 MP2 graphics controller, which allows you to transfer high-quality video stream to the screen in cutting-edge 4K format at a maximum frame rate of 60fps. This model has 2 GB DDR4 multi-threaded RAM and 16 GB eMMC flash memory, which significantly speeds up the work of the set-top box (fast writing, reading and processing information, fast applications). To expand the permanent memory, there is a slot for memory cards microSD up to 64GB. Mecool KM6 Classic runs on Google-certified Android TV 10.0 operating system, which ensures fast and stable performance. The system is pre-installed with a full set of applications required by the user, and there is also access to the Google Play application library. The presence of a remote control with a built-in microphone will make it easier to control the set-top box using voice commands. The remote control itself is compact and has an ergonomic shape, so it fits perfectly in your hand. The remote control is connected to the set-top box using Bluetooth technology.`,
    price: 67.54,
    discountPrice: 67.54,
    discountPercentage: 0,
    rating: 3.74,
    stock: 52,
    color: 'black',
    brand: 'Mecool',
    category: 'TV-box',
    images: [
      '../../assets/img/64143195731-l.jpg',
      '../../assets/img/64143195732-l.jpg',
      '../../assets/img/64143195733-l.jpg',
    ],
  },
  {
    id: 38,
    title: 'Harper ABX-230',
    description: `The compact multifunctional media player Harper ABX-230 runs on the Android 9.0 platform, which makes it possible to connect your TV to popular online cinemas, listen to music and download any applications from PlayMarket. The TV box plays 4K UHD video at 60 frames per second, creating a "presence effect". A 1.2GHz ARM Cortex-A53 processor, Mali-450 MP graphics accelerator and 2GB RAM provide the performance you need. 8 GB of internal memory is provided for storing files. The set-top box is equipped with a 2.4 GHz Wi-Fi wireless module, and is also compatible with new and old generation TVs due to the presence of two video outputs: HDMI and AV. It is easy to connect and does not require additional configuration.`,
    price: 39.59,
    discountPrice: 37.61,
    discountPercentage: 5,
    rating: 3.94,
    stock: 5,
    color: 'black',
    brand: 'Harper',
    category: 'TV-box',
    images: [
      '../../assets/img/51717649991-l.jpg',
      '../../assets/img/51717649992-l.jpg',
      '../../assets/img/51717649993-l.jpg',
      '../../assets/img/51717649994-l.jpg',
    ],
  },
  {
    id: 39,
    title: 'Ritmix RBK-616',
    description: `Ritmix RBK-616 will be an ideal find for those who prefer an active lifestyle. Due to its light weight and size, the reader does not take up much space, which allows you to take it with you anywhere. The model has an E-ink Carta screen that does not visually differ from ordinary paper, does not glare in the sun and consumes very little energy. The practical arrangement of the function keys allows you to fully control the device even with one hand. 4 GB of internal memory + a slot for a memory card up to 32 GB - this is a whole library that is always at hand!`,
    price: 90.62,
    discountPrice: 87.9,
    discountPercentage: 3,
    rating: 3.6,
    stock: 35,
    color: 'black',
    brand: 'Ritmix',
    category: 'ebook',
    images: ['../../assets/img/92954458711-l.jpg', '../../assets/img/92954458712-l.jpg'],
  },
  {
    id: 40,
    title: 'Apple Watch Series 7',
    description: `Apple Watch Series 7 GPS is a smart watch from one of the most popular and well-known brands in the world of technology. Compared to its predecessor, they received a larger display, increased shock resistance, even faster charging and expanded health monitoring functions. The Apple Watch Series 7 GPS is available in several color options and has a wide variety of straps to choose from. The watch is equipped with a rectangular OLED display and Always-On mode. They are able to monitor pulse, blood oxygen saturation, activity during jogging and training. The aluminum body of the device is protected against dust, moisture and minor shocks according to the IP6X/WR50 standard. Additionally, the Apple Watch Series 7 GPS has built-in NFC and GPS.`,
    price: 417,
    discountPrice: 371.13,
    discountPercentage: 11,
    rating: 4.7,
    stock: 55,
    color: 'green',
    brand: 'Apple',
    category: 'smartwatch',
    images: ['../../assets/img/18459214551-l.jpg', '../../assets/img/18459214552-l.jpg'],
  },
  {
    id: 41,
    title: 'HP ProBook',
    description: `Notebook HP ProBook 450 G8 will be a reliable and loyal assistant, accompanying its owner in the process of every outdoor event. A 2-core Intel Core i3 1115G4 processor and 8 GB of RAM are responsible for the prompt solution of any of the tasks. The safety of your data is guaranteed by the built-in fingerprint, completely eliminating the risk of unauthorized access.
    The standard 15.6-inch screen with a refresh rate of 60 Hz will surprise you with incredibly detailed and rich images in Full-HD resolution. The Wi-Fi 6 module will provide you with worldwide access to the World Wide Web without a single delay. And the powerful battery of the HP ProBook 450 G8 laptop will not disappoint you with a sudden low level of charge for several hours. The cover of the device instantly unfolds 180 degrees, thereby allowing you to demonstrate the necessary graphics or drawings.`,
    price: 1019.25,
    discountPrice: 866.36,
    discountPercentage: 15,
    rating: 4.35,
    stock: 12,
    color: 'silver',
    brand: 'HP',
    category: 'laptop',
    images: [
      '../../assets/img/77879135071-l.jpg',
      '../../assets/img/77879135072-l.jpg',
      '../../assets/img/77879135073-l.jpg',
    ],
  },
  {
    id: 42,
    title: 'Aspor Z6B',
    description: `Smart watches only work with a SIM card that supports the 2G communication standard! Be sure to watch the connection video! Children's smart watch Z6 in a fashionable design. Z6 smart watch with GPS tracker function, SOS button and camera, SIM card support will suit both boys and girls. Location determination may be inaccurate. Accuracy depends on the quality of 2G coverage and distance from cell towers. Using the children's watch, the child will be able to call pre-set numbers, exchange voice messages with parents and, if necessary, give an alarm to adults. And parents will be able at any time without the knowledge of the child to listen to what their child is doing at the moment. The watch has the main functions, watch tracking, a phone book with 10 numbers, three numbers for emergency messages, turning off via a smartphone in remote mode - the child will not be able to turn off the watch himself. Setracker2 App! They do not work with Tele2! The phone must support Google Apps!`,
    price: 14.5,
    discountPrice: 14.5,
    discountPercentage: 0,
    rating: 3.28,
    stock: 3,
    color: 'blue',
    brand: 'Aspor',
    category: 'smartwatch',
    images: [
      '../../assets/img/92687736461-l.jpg',
      '../../assets/img/92687736462-l.jpg',
      '../../assets/img/92687736463-l.jpg',
    ],
  },
  {
    id: 43,
    title: 'Dell Inspiron 24',
    description: `A sleek 23.8" all-in-one designed for streaming and surfing the web. With InfinityEdge display, pop-up webcam and Dell Cinema technology. This position may not be available in the selected business segment. Bright image. The 23.8" FHD InfinityEdge display with 8mm bezels looks amazing from almost any angle. Modern and comfortable design. Enjoy stylish design and work in comfort with a stable and compact stand, directional acoustic bar and under-display keyboard compartment. Pleasant sound. A forward-firing acoustic panel with speakers professionally tuned with Waves MaxxAudio Pro technology not only adds style to the unit, but also enhances the sound quality. Stylish workspace. The elegant silver model is available with a choice of two bases: bow or A-shaped. The arc stand is an easel stand with forward facing speakers with a silver mesh finish for better sound quality. In the A-stand model, the display rests on two triangular legs. The A-stand is offered with forward-firing mesh-covered speakers.`,
    price: 1839.2,
    discountPrice: 1434.58,
    discountPercentage: 22,
    rating: 4.58,
    stock: 3,
    color: 'black',
    brand: 'Dell',
    category: 'monoblock',
    images: [
      '../../assets/img/52026264101-l.jpg',
      '../../assets/img/52026264102-l.jpg',
      '../../assets/img/52026264103-l.jpg',
      '../../assets/img/52026264104-l.jpg',
    ],
  },
  {
    id: 44,
    title: 'Apple iMac Retina 4K',
    description: `A desktop that immerses you in content. Literally. This idea is at the heart of the modern iMac - and today it is more relevant than ever. Brand-new processors, innovative graphics technologies, advanced storage, and impressive bandwidth connectors are all part of the new iMac. And its Retina display is able to bring any picture to life, because it has no equal among iMacs in terms of brightness and color quality. Working on iMac is now even more interesting and exciting.`,
    price: 2552.67,
    discountPrice: 2144.24,
    discountPercentage: 16,
    rating: 4.72,
    stock: 31,
    color: 'silver',
    brand: 'Apple',
    category: 'monoblock',
    images: [
      '../../assets/img/27558018552-l.jpg',
      '../../assets/img/27558018553-l.jpg',
      '../../assets/img/27558018554-l.jpg',
      '../../assets/img/27558018555-l.jpg',
    ],
  },
  {
    id: 45,
    title: 'Ugoos X4 IPTV',
    description: `Ugoos X4 Pro is a new version of smart set-top box with 4GB and 32GB RAM and flash memory, respectively, based on the Amlogic S905X4 quad-core processor, which uses ARM Cortex-A55 processors, which slightly improves performance and energy efficiency compared to Cortex-A53 and no less productive graphics chip Mali-G31 MP2. The model runs on the Android 11 operating system with a proprietary shell from Ugoos.
    The presence of the HDMI version 2.1 interface allows you to evaluate the quality of 4K at 75 Hz with support for CEC, HDCP 2.2, HDR. In addition, the interface supports the transmission of multi-channel audio.
    The built-in wireless 2-band Wi-Fi module complies with the 802.11 ac standard, the connection speed can reach 867 Mbps and the gigabit Ethernet port allows you to connect to a high-speed Internet connection by wire. To connect external wireless devices, there is a built-in Bluetooth 4.2 module with LE technology.
    The set-top box can easily handle both 4K 60 fps streaming from YouTube and processing modern 3D games from Google Play at a high level of detail. This is a great device for home use and easy to take with you on a trip or business trip.`,
    price: 116.1,
    discountPrice: 110.29,
    discountPercentage: 5,
    rating: 3.69,
    stock: 1,
    color: 'black',
    brand: 'Ugoos',
    category: 'TV-box',
    images: [
      '../../assets/img/36944848201-l.jpg',
      '../../assets/img/36944848202-l.jpg',
      '../../assets/img/36944848203-l.jpg',
      '../../assets/img/36944848204-l.jpg',
    ],
  },
  {
    id: 46,
    title: 'Xiaomi 11T Pro',
    description: `The Qualcomm Snapdragon 888 5G processor significantly improves the performance of the smartphone compared to the previous generation of the chipset. Provides the highest performance and low power consumption.
    The gadget uses Xiaomi HyperCharge 120W charging - 100% charge in just 17 minutes! If you charge the device for 10 minutes, then this is enough to watch the video for 7 hours or 11 hours of calls.
    AMOLED display with over 1 billion colors. The Xiaomi 11T Pro's 6.67-inch screen is excellent in terms of brightness, contrast, color calibration and resolution. The frame rate reaches 120 Hz. Supports HDR10+, Dolby Vision and memes.
    The smartphone's dual speakers were developed by Harman/Kardon. They deliver high quality 360° surround sound with Dolby Atmos technology.`,
    price: 764.43,
    discountPrice: 695.63,
    discountPercentage: 8.5,
    rating: 4.55,
    stock: 34,
    color: 'blue',
    brand: 'Xiaomi',
    category: 'smartphone',
    images: [
      '../../assets/img/72101524531-l.jpg',
      '../../assets/img/72101524532-l.jpg',
      '../../assets/img/72101524533-l.jpg',
      '../../assets/img/72101524534-l.jpg',
    ],
  },
  {
    id: 47,
    title: 'Apple Watch Series 6',
    description: `Apple Watch Series 6 lets you measure your blood oxygen levels with a stunning new sensor and dedicated app. View your fitness metrics on an improved, always-on Retina display that's now 2.5x brighter outdoors, in idle mode, with your watch hand down. Set up a set of pre-sleep activities and track your sleep patterns. Answer calls and messages right from your wrist. It's a powerful device that makes it much easier to live a healthier, more active and connected life.`,
    price: 317,
    discountPrice: 291.64,
    discountPercentage: 7.5,
    rating: 4.43,
    stock: 85,
    color: 'red',
    brand: 'Apple',
    category: 'smartwatch',
    images: [
      '../../assets/img/71563283061-l.jpg',
      '../../assets/img/71563283062-l.jpg',
      '../../assets/img/71563283064-l.jpg',
      '../../assets/img/71563283065-l.jpg',
    ],
  },
  {
    id: 48,
    title: 'Philips B-line 240B9',
    description: `Push the boundaries of what's possible with this Philips B Line frameless monitor with a 16:10 aspect ratio. This eco-friendly monitor of the next level has many useful functions.
    The Philips monitor is a simple solution for laptop with a docking station and connection via a single cable. A single USB cable with dual mesh and Type-C and Type-A connectors provides video playback and Ethernet, DisplayLink and charging functions. The Windows Hello webcam guarantees increased security.`,
    price: 393,
    discountPrice: 365.49,
    discountPercentage: 6.5,
    rating: 3.9,
    stock: 24,
    color: 'black',
    brand: 'Philips',
    category: 'monitor',
    images: [
      '../../assets/img/44858939661-l.jpg',
      '../../assets/img/44858939662-l.jpg',
      '../../assets/img/44858939663-l.jpg',
      '../../assets/img/44858939665-l.jpg',
    ],
  },
  {
    id: 49,
    title: 'HP Pavilion 259P3EA',
    description: `The HP Pavilion all-in-one with its impeccable design, incredible power and performance is ideal in everything. Thanks to it, you will not only cope with the most difficult projects, but also get special pleasure from watching your favorite movies. The wonderful combination of form and functionality of this computer will decorate any home.
    High performance for entertainment, gaming and multitasking.
    Meets all modern requirements. A screen with almost imperceptible frames, a refined thin body and leather inserts - this monoblock is the very embodiment of elegance. Conveniently located ports on the side and back of the device provide unhindered access and allow you to get rid of unnecessary wires.
    Easily stream and view videos with a retractable camera with privacy technology that safely retracts when not in use. A powerful and reliable processor will help you cope with the most difficult tasks.`,
    price: 772.5,
    discountPrice: 718.42,
    discountPercentage: 6.7,
    rating: 4.56,
    stock: 45,
    color: 'white',
    brand: 'HP',
    category: 'monoblock',
    images: [
      '../../assets/img/23436256191-l.jpg',
      '../../assets/img/23436256192-l.jpg',
      '../../assets/img/23436256193-l.jpg',
      '../../assets/img/23436256194-l.jpg',
    ],
  },
  {
    id: 50,
    title: 'Xiaomi 4K Mi Box S',
    description: `Mi Box S is a bright representative of the new generation of TV set-top boxes. It has a rather powerful "stuffing" and a number of features that bring it to a new level among other Mi Box models.
    The TV set-top box has 2 GB of RAM and 8 GB of flash memory. At the same time, the gadget can play video content in 4K (3840 x 2160) Ultra HD quality, which will allow you to enjoy a clear, saturated and contrasting image while watching movies or educational programs. In addition, the device has acquired the intelligent control system Google Assistant and SmartCast, which expand the capabilities of the device.
    In order to quickly process information and quickly perform user tasks, the TV set-top box has a powerful Amlogic Cortex-A53 Quad-Core 64-bit processor and Mali-450 graphics.
    As for the connection interface, it is, as always, universal. The Mi Box S TV set-top box is one of the first of its kind, which supports the DOLBY + DTS format and provides high sound quality.`,
    price: 64,
    discountPrice: 57.6,
    discountPercentage: 9.5,
    rating: 4.38,
    stock: 77,
    color: 'black',
    brand: 'Xiaomi',
    category: 'TV-box',
    images: [
      '../../assets/img/89856120651-l.jpg',
      '../../assets/img/89856120652-l.jpg',
      '../../assets/img/89856120653-l.jpg',
      '../../assets/img/89856120654-l.jpg',
    ],
  },
];
