export const productData = [
  {
    id: 1,
    title: 'Wireless mouse',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: 'Mouse',
    category: 'Mouses',
    thumbnail: 'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
    images: [
      '//cdn.shopify.com/s/files/1/0604/5021/0008/products/1_22926035-6bb9-446c-b307-e41f66fb7c06.jpg?v=1635741603',
      '//cdn.shopify.com/s/files/1/0604/5021/0008/products/2_8e04415d-fcf4-4a84-9c42-786a27f08860.jpg?v=1635741603',
      '//cdn.shopify.com/s/files/1/0604/5021/0008/products/3_14c0490f-8312-410c-90cb-682923f1c3b9.jpg?v=1635741603',
      '//cdn.shopify.com/s/files/1/0604/5021/0008/products/4_798d3e36-2843-41f6-bb54-4c0b3e6f6995.jpg?v=1635741603',
    ],
  },
  {
    id: 2,
    title: 'iPhone 9',
    description: 'An apple mobile which is nothing like apple',
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
    images: [
      '../../assets/img/iphone-9.jpg',
      'https://i.dummyjson.com/data/products/1/2.jpg',
      'https://i.dummyjson.com/data/products/1/3.jpg',
      'https://i.dummyjson.com/data/products/1/4.jpg',
      'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
    ],
  },
  {
    id: 3,
    title: 'iPhone X',
    description:
      'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...',
    price: 899,
    discountPercentage: 17.94,
    rating: 4.44,
    stock: 34,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/2/1.jpg',
      'https://i.dummyjson.com/data/products/2/2.jpg',
      'https://i.dummyjson.com/data/products/2/3.jpg',
      'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    ],
  },
  {
    id: 4,
    title: 'Samsung Universe 9',
    description: "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discountPercentage: 15.46,
    rating: 4.09,
    stock: 36,
    brand: 'Samsung',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/3/thumbnail.jpg',
    images: ['https://i.dummyjson.com/data/products/3/1.jpg'],
  },
  {
    id: 5,
    title: 'OPPOF19',
    description: 'OPPO F19 is officially announced on April 2021.',
    price: 280,
    discountPercentage: 17.91,
    rating: 4.3,
    stock: 123,
    brand: 'OPPO',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/4/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/4/1.jpg',
      'https://i.dummyjson.com/data/products/4/2.jpg',
      'https://i.dummyjson.com/data/products/4/3.jpg',
      'https://i.dummyjson.com/data/products/4/4.jpg',
      'https://i.dummyjson.com/data/products/4/thumbnail.jpg',
    ],
  },
  {
    id: 6,
    title: 'Huawei P30',
    description:
      'Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.',
    price: 499,
    discountPercentage: 10.58,
    rating: 4.09,
    stock: 32,
    brand: 'Huawei',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/5/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/5/1.jpg',
      'https://i.dummyjson.com/data/products/5/2.jpg',
      'https://i.dummyjson.com/data/products/5/3.jpg',
    ],
  },
  {
    id: 7,
    title: 'MacBook Pro',
    description: 'MacBook Pro 2021 with mini-LED display may launch between September, November',
    price: 1749,
    discountPercentage: 11.02,
    rating: 4.57,
    stock: 83,
    brand: 'Apple',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/6/thumbnail.png',
    images: [
      'https://i.dummyjson.com/data/products/6/1.png',
      'https://i.dummyjson.com/data/products/6/2.jpg',
      'https://i.dummyjson.com/data/products/6/3.png',
      'https://i.dummyjson.com/data/products/6/4.jpg',
    ],
  },
  {
    id: 8,
    title: 'Samsung Galaxy Book',
    description: 'Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched',
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: 'Samsung',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/7/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/7/1.jpg',
      'https://i.dummyjson.com/data/products/7/2.jpg',
      'https://i.dummyjson.com/data/products/7/3.jpg',
      'https://i.dummyjson.com/data/products/7/thumbnail.jpg',
    ],
  },
  {
    id: 9,
    title: 'Microsoft Surface Laptop 4',
    description:
      'Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.',
    price: 1499,
    discountPercentage: 10.23,
    rating: 4.43,
    stock: 68,
    brand: 'Microsoft Surface',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/8/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/8/1.jpg',
      'https://i.dummyjson.com/data/products/8/2.jpg',
      'https://i.dummyjson.com/data/products/8/3.jpg',
      'https://i.dummyjson.com/data/products/8/4.jpg',
      'https://i.dummyjson.com/data/products/8/thumbnail.jpg',
    ],
  },
  {
    id: 10,
    title: 'Infinix INBOOK',
    description: 'Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty',
    price: 1099,
    discountPercentage: 11.83,
    rating: 4.54,
    stock: 96,
    brand: 'Infinix',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/9/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/9/1.jpg',
      'https://i.dummyjson.com/data/products/9/2.png',
      'https://i.dummyjson.com/data/products/9/3.png',
      'https://i.dummyjson.com/data/products/9/4.jpg',
      'https://i.dummyjson.com/data/products/9/thumbnail.jpg',
    ],
  },
  {
    id: 11,
    title: 'HP Pavilion 15-DK1056WM',
    description: 'HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10',
    price: 1099,
    discountPercentage: 6.18,
    rating: 4.43,
    stock: 89,
    color: 'silver',
    brand: 'HP Pavilion',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/10/thumbnail.jpeg',
    images: [
      'https://i.dummyjson.com/data/products/10/1.jpg',
      'https://i.dummyjson.com/data/products/10/2.jpg',
      'https://i.dummyjson.com/data/products/10/3.jpg',
      'https://i.dummyjson.com/data/products/10/thumbnail.jpeg',
    ],
  },
  {
    id: 12,
    title: 'Realme 9 Pro+',
    description:
      'The Realme 9 Pro+ smartphone has 3 main cameras: 50 + 8 + 4 megapixels that allow you to shoot 4K video, take excellent portraits with bokeh effect, panoramic shots and photos of distant objects, slow motion at 960 fps. The 16 MP front camera makes it possible to take great selfies. The Super AMOLED display with a resolution of 2400x1080 will amaze you with bright, rich and deep blacks. A capacious 4500 mAh battery is enough for a long battery life. The supplied 60W power adapter will help you quickly replenish the charge. An in-display fingerprint scanner and software face unlock protect your data if your device is lost. An NFC module is provided for contactless payment.',
    price: 368,
    discountPercentage: 0,
    rating: 4.58,
    stock: 5,
    color: 'black',
    brand: 'Realme',
    category: 'smartphones',
    thumbnail: '../../assets/img/71114058551.jpg',
    images: [
      '../../assets/img/71114058551-l.jpg',
      '../../assets/img/71114058553-l.jpg',
      '../../assets/img/71114058554-l.jpg',
      '../../assets/img/71114058555-l.jpg',
    ],
  },
  {
    id: 13,
    title: 'Xiaomi Redmi Watch 2 Lite Global',
    description:
      'Get in shape, start right now. 100+ workout modes. Track your exercises like an expert. Switch freely between over 100 watch faces with multiple trend-setting combinations to suit your mood.',
    price: 70.65,
    discountPercentage: 4.23,
    rating: 3.85,
    stock: 12,
    color: 'white',
    brand: 'Xiaomi',
    category: 'smartwatches',
    thumbnail: '../../assets/img/48367418351.jpg',
    images: [
      '../../assets/img/48367418351-l.jpg',
      '../../assets/img/48367418352-l.jpg',
      '../../assets/img/48367418353-l.jpg',
    ],
  },
  {
    id: 14,
    title: 'Huawei MatePad Pro',
    description:
      'The color design of Huawei MatePad Pro is inspired by nature. The midnight gray body is covered with a layer of fiberglass that reflects the light and reflects your unique style. Compact and lightweight, weighing only 460g, it is easy to carry everywhere with you. It feels like a simple sheet of paper in a backpack.The hidden antenna gives the tablet a sleek and finished look, while the thin, slightly rounded bezel makes the tablet comfortable to use.',
    price: 707.8,
    discountPercentage: 4.23,
    rating: 3.85,
    stock: 12,
    color: 'silver',
    brand: 'Huawei',
    category: 'tablets',
    thumbnail: '../../assets/img/14380352311.jpg',
    images: ['../../assets/img/14380352311-l.jpg', '../../assets/img/14380352312-l.jpg'],
  },
];
